### ISSUE TITLE
Please link to http://reprap.org/wiki/Prusa_Mendel

### ISSUE THREAD

**Issue by D1plo1d** [josefprusa/PrusaMendel#1]
From what I understand we are documenting this primarily on the reprap wiki (http://reprap.org/wiki/Prusa_Mendel).. even if this was not intially the plan the documentation there is now much further along then the README file on github. To avoid confusion could you please simply provide a link to the reprap wiki documentation in that file so that people are not trying to build Prusas with out of date or less complete documentation then they have to.

PS. Prusa Mendel really is an excellent improvement over Mendel, cheers for making things better!

**Comment by kliment** [comment]
Done.

**Comment by D1plo1d** [comment]
Thanks!
