### ISSUE TITLE
Nitpick in bar-clamp

### ISSUE THREAD

**Issue by DaleDunn** [josefprusa/PrusaMendel#10]
Hello, and thanks for all the great work so far.

This is possibly inconsequential or done for extrusion reasons, but one side of the bar clamp is 0.5mm thicker than the other. 

The problem seems to be in this line:
translate([9, outer_diameter/2+1, 0])cube([18,05,20]);

It should probably be something like:
translate([9, outer_diameter-slot_width/2, 0])cube([18,05,20]);

**Comment by josefprusa** [comment]
You are right thanks!! This shouldn't affect the function of the part, Ill repair it, but its not high priority :-)

**Comment by nophead** [comment]
// PRUSA Mendel  
// Bar clamp
// Used for joining 8mm rods
// GNU GPL v2
// Josef PrÅ¯Å¡a
// josefprusa@me.com
// prusadjs.cz
// http://www.reprap.org/wiki/Prusa_Mendel
// http://github.com/prusajr/PrusaMendel

include <configuration.scad>

module barclamp(){
outer_radius = m8_diameter/2+3.3;
slot_width = 5;

```
difference(){
    union(){

        translate([outer_radius, outer_radius, 0])
            cylinder(h = outer_radius * 2, r = outer_radius, $fn = 20);

        translate([outer_radius, 0, 0])
            cube([17.5,outer_radius * 2, outer_radius * 2]);
    }


    translate([9, outer_radius - slot_width / 2, 0])
        cube([18, slot_width, 20]);

    translate([outer_radius, outer_radius, 0]) 
        cylinder(h = 20, r = m8_diameter / 2, $fn = 18);

    translate([17, 17, 7.5]) rotate([90, 0, 0])
        cylinder(h = 20, r = m8_diameter / 2, $fn = 10);
}
```

}

barclamp();
