### ISSUE TITLE
Weak Z Coupling 

### ISSUE THREAD

**Issue by pawl** [josefprusa/PrusaMendel#29]
I see a lot of people (including myself) having trouble with the Z Coupling in this repository cracking due to stress. 

Maybe we should consider a design like Nopheads?: http://www.thingiverse.com/thing:9622

It looks like Nophead's design is the one PrusaJr prefers: http://www.flickr.com/photos/prusajr/6045851714/in/photostream/lightbox/

**Comment by brad** [comment]
Agreed, nophead's couplings work incredibly well. I went through several of the default couplings and they all broke. I never worry about my couplings breaking now.

**Comment by pawl** [comment]
I wish I gave them a try before I opted for drastic measures. 

Aluminum Z Coupling (from Ebay): http://4.bp.blogspot.com/-p_TQJDYvM00/TqpZ1Kh7hiI/AAAAAAAAABQ/rTbXFCHLVAs/s1600/IMAG0232.jpg

**Comment by pawl** [comment]
This was replaced in Iteration 2. Fixed
