### ISSUE TITLE
y carriage missing?

### ISSUE THREAD

**Issue by D1plo1d** [josefprusa/PrusaMendel#3]
I've now built most of my Prusa Mendel but I've now run into 2 problems:
1) I have yet to find the y carriage in github that is shown in this vid: http://www.youtube.com/watch?v=0MvUD-tuOX0

2) The Z shaft couplers don't work (as Prusajr mentioned earlier)

The first problem is the important one. Could you please post the y carriage or let me know where to find it?

Thanks,
Rob

**Comment by D1plo1d** [comment]
Oh, also the y-idler is missing but I think theres some debate as to whether that is intentional or not.

**Comment by josefprusa** [comment]
Look at the latest post on blog.reprap.org, all problems are not problems at all. The parts you mentioned are now not needed at all!

**Comment by D1plo1d** [comment]
cool, I was thinking it would be more complex :)

**Comment by josefprusa** [comment]
No, its that ridiculously simple :-)
