### ISSUE TITLE
LM8UU X-Ends are weak, and easily broken

### ISSUE THREAD

**Issue by Lodran** [josefprusa/PrusaMendel#33]
At the point where the ziptie cutout is made, the thickness of the walls drop to a point where it becomes very easy to break the part while removing it from the build plate.

I would suggest increasing the inner diameter of the ziptie cutout by 1mm.

**Comment by jglauche** [comment]
I do think this is fixed with my latest update; requiring zip ties for the holders. They are not prone to breakage anymore.
