### ISSUE TITLE
Flanged bearing guides can cause print issues

### ISSUE THREAD

**Issue by DaleDunn** [josefprusa/PrusaMendel#37]
Some people are having print quality issues due to the belts' teeth rubbing on the bearing guide's flange. I thought you might be interested in trying a crowned pulley like the one I just tested. I think it would simplify the build somewhat as well, as it's only one printed part per pulley.

I have a more complete description on Thingiverse:
http://www.thingiverse.com/thing:14117

http://www.youtube.com/watch?feature=player_profilepage&v=foQmpN2twf8
https://github.com/DaleDunn/PrusaMendel/commit/f104c989a8dd936e654f2835218a9a5363458494

**Comment by josefprusa** [comment]
Hi great! I like the idea! But it requires wide belts (loot wider then high, thats why T5 wont work) and proper tensioning. Which makes it too much a variable. I can solve the problem by making sides of the now present bearing guides conical.
