### ISSUE TITLE
wade-big.scad nut size incorrect

### ISSUE THREAD

**Issue by ellensp** [josefprusa/PrusaMendel#39]
The nut size in wade-big.scad is still presumes edge to edge measurements for m8_nut_diameter

ie line 53 "cylinder($fn=6,r=m8_nut_diameter/2-0.5,h=nut_trap_depth+1);"

Should read something like "nut(m8_nut_diameter,nut_trap_depth+1,true);"

**Comment by athlonx** [comment]
I changed the -.05 to +.05 and it fits nicely.

**Comment by pawl** [comment]
I'm having the same issue, it's like 2mm too small.

http://imgur.com/q9RZQ

**Comment by pawl** [comment]
This should be fixed in the restructure branch. It just needs to be merged with the master branch.
