### ISSUE TITLE
are the .scad files for the below stl's available?

### ISSUE THREAD

**Issue by chgray** [josefprusa/PrusaMendel#4]
z-bar-top-clamp_4off.stl
pulley.stl
y-motor-bracket_1off.stl

**Comment by kliment** [comment]
They were not. We are no longer using z-bar-top-clamp, and the replacement does have a scad file. I am also including the pulley scad file. I have created a new y-motor-bracket to replace the original, this requires a dxf file and the scad file is available. I will upload the files shortly. Why do you ask? Is there a change you would like to make?

**Comment by twaffle** [comment]
Kliment, you may want to look at my y-motor-bracket as an alternative.

**Comment by chgray** [comment]
I'm in the US and getting the metric parts costs a lot of money, I'm building http://www.thingiverse.com/derivative:4552.  Having a supported variable to enable these in the configuration.scad would be great (or have two configuration.scads)

This is the first time I'm making a Prusa so I'm not sure whats needed :-)  the Makerbot.scad  makes reference these files.  Should these parts just be removed from the Makerbot.scad?

In order to get build plate 1 to all fit on the makerbot I did have to move the frame-vertex 20 or 30mm

**Comment by kliment** [comment]
Hello. I have just changed the files and made the ones that are still required parametric. The exact list of necessary parts is on the reprap wiki at http://www.reprap.org/wiki/Prusa_Mendel (See BOM). I am about to upload the updated .scad files. You can then change the values in configuration.scad to your heart's content.
