### ISSUE TITLE
nema 17 holes covered in wade.scad

### ISSUE THREAD

**Issue by ellensp** [josefprusa/PrusaMendel#40]
When compiling you get "WARNING: Ignoring unknown variable 'layer_height'."

This is used in module motor_mount_holes(), without it the holes don't protrude threw the object

**Comment by ellensp** [comment]
The top nut inserts in wade.scad also have the same issue and end up to small.

Line 425 "cube([m3_nut_diameter*cos(30),10,idler_nut_thickness],center=true);" should be
"cube([m3_nut_diameter,10,idler_nut_thickness],center=true);"

Also in the idler

Line 539 "cylinder(h=3,r=m3_nut_diameter/2,$fn=6);"  should be something like
"nut(m3_nut_diameter,3,true);"

**Comment by cyrozap** [comment]
How should the "WARNING: Ignoring unknown variable 'layer_height'." problem be fixed? I'm trying to compile it now and I'm getting the same errors.

**Comment by ellensp** [comment]
I added "layer_height = 0.25;" to my configuration.scad

**Comment by cyrozap** [comment]
That works for me. Thanks!
