### ISSUE TITLE
BOM is far from complete

### ISSUE THREAD

**Issue by Shaun1** [josefprusa/PrusaMendel#45]
Structural rods (with dimensions) , motors, gears etc. should be listed in BOM with adequate detail.

**Comment by unrepentantgeek** [comment]
Could you update the BOM with the lengths of rods?  The length of the x axis smooth rods is especially criticial in this build.

**Comment by pawl** [comment]
I'm thinking the x axis smooth rod needs to be exactly 400mm to fit with just 2 washers and a nut between the z-motor mount and the frame vertex, but I'm trying to get someone to verify that: http://forums.reprap.org/read.php?151,110832

So the change in https://github.com/prusajr/PrusaMendel/blob/master/docs/bill-of-materials.txt will probably be:

# Rods and Bars
- 1x M8x30 threaded rod (Idler)
- 1x M8x20 threaded rod (Extruder Idler)
- 6x M8×370mm
- 4x M8×294mm
- 3x M8×440mm  
- 2x M8×210mm  
- 2x 8mm×400mm smooth rods (X axis)  
- 2x 8mm×406mm smooth rods (Y axis)  
- 2x 8mm×350mm smooth rods (Z axis)
