### ISSUE TITLE
Bed drilling template for lm8uu wrong

### ISSUE THREAD

**Issue by metzench** [josefprusa/PrusaMendel#52]
The Bed drilling template for lm8uu has the wrong hole distances. It should have 28mm like the template for lme8uu has.

**Comment by henrikbrixandersen** [comment]
I can confirm this issue.

**Comment by josefprusa** [comment]
You are right, of course. Sorry for that, my mistake. Will fix.

**Comment by josefprusa** [comment]
Fixed
