### ISSUE TITLE
X idler/motor brackets should accomodate use of bolts

### ISSUE THREAD

**Issue by bgamari** [josefprusa/PrusaMendel#63]
While I can understand the desire to minimize the use of vitamins, it seems to me that the current friction-fit between the idler/motor brackets and the X axis' smooth rods is a poor trade-off. The brackets I were sold in my initial parts buy had nut traps and bolt holes to retain the X axis smooth rods. When working with poorly aligned machines (e.g. poorly sized Z axis couplers), I have found it invaluable to be able to lengthen the X axis smooth rods a tad, allowing me to apply force on the Z axis bushings and minimize X axis wobble. This is not possible with a mere friction fit. Moreover, I've noticed that even without this pre-loading, the friction fit brackets permit noticeably greater wobble than the old parts due to flexing of the pressure-applying finger.

**Comment by jglauche** [comment]
I'm sorry, I don't see your problem here. I have 5 Prusa Mendels now with push fit X ends and they all work perfectly with the 2 part couplings in the repository.
When you recently upgrade from the old non-pushfit X-ends you need to make sure your X rods are cut to the same length, then you need to readjust one of your Z motor mounts (using nuts/washers) to be the exact length as the whole X stage. If you miss that, you'll get terrible results.

**Comment by bgamari** [comment]
You demonstrate my point exactly. The screw solution has one great advantage: it is very forgiving. It seems that the decision to use the push-fit coupling trades off cheap and readily available screws for a less forgiving solution requiring greater control over material preparation (i.e. smooth rod length). In light of the fact that the screw solution produces a far more stable platform in the face of an imperfect Z coupling, this seems like a very poor trade-off indeed. If nothing else the new design should allow the builder to use screws if the need should arise.

**Comment by jglauche** [comment]
Well, you can always use the old files if the new ones doesn't work in your setup. But I really recommend to print out new couplings and do the steps as I recommended. 

For new builds, it's easier to build the frame according to the X stage. Once you have set the Z motor mounts exactly as long apart as the X ends (smooth rod to smooth rod) while building the frame, you have zero calibration effort at that point later.
