### ISSUE TITLE
M3 holes size

### ISSUE THREAD

**Issue by nophead** [josefprusa/PrusaMendel#7]
The M4 hole size is 4.5, which is reasonable but the M3 is 4.4, i.e. almost the same. Looks like a typo as 3.4 would be more reasonable.

**Comment by josefprusa** [comment]
Actual settings comes out for me at 3.5mm, for some guys it comes out as 3mm and for some even smaller. I want it to work for most ppl out of the box. I hope it's reasonable.
I suggest then to change configuration, compile calibration.scad if its ok, type "make parts" and you have precise holes.

**Comment by nophead** [comment]
Yes I have done but they can't both be right as sensible defaults. Who has a machine where 4.5 comes out about 4 and 4.4 comes out about 3? The latest change that made some holes M3 instead of M4 made no appreciable difference, 0.1mm. They are both around 4mm when I print them. Presumably they are both about 3.5mm when you print them.

**Comment by nophead** [comment]
Sorry, my mistake your M4 holes are 5mm, not 4.5. I misread the .4 from 16.4 for an M8 nut. M8 nuts are actually 13mm so again these are way too big. Do you really have a machine that prints 16.4 hexagons just over 13mm?
I see I need to review every single hole in the project and change the config plus some of the rest of the files because not all holes are parametric.

**Comment by josefprusa** [comment]
The nuts diameters have to be measured from corner to opposite corner, which in our M8 case is about 15mm :-)
Please if you find some unparametric hole and repair it, commit the change to repo, or mail me the file if commit it for you!
